baseURL = "http://busted.link"
title = "an unequivocally big dumb ape"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 6
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
author = "monke"
description = "enthusiastic chimp noises"
keywords = "blog,developer,personal"
info = ["physical and digital security enjoyer"]
avatarURL = "images/monke.jpg"
dateFormat = "January 2, 2006"
since = 2009
# Right To Left, shift content direction for languagues such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "dark"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = true 
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
customSCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

# scriptsrc = [
#   "'self'",
#   "'unsafe-inline'",
#   "https://www.google-analytics.com",
#   "https://cdn.jsdelivr.net/",
# ]
# prefetchsrc = ["'self'"]
# # connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
# connectsrc = ["'self'", "https://www.google-analytics.com"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/bigdumbape/"

[[params.social]]
name = "Twitter"
icon = "fa-brands fa-twitter fa-2x"
weight = 3
url = "https://twitter.com/bigdum_bape/"

[[params.social]]
name = "Medium"
icon = "fa-brands fa-medium fa-2x"
weight = 5
url = "https://medium.com/@bigdumbape"

[[params.social]]
name = "RSS"
icon = "fa-solid fa-rss fa-2x"
weight = 6
url = "https://bigdumbape.github.io/index.xml"
rel = "alternate"
type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact me"
weight = 5
url = "contact/"

