baseURL = "https://bigdumbape.github.io"
languageCode = "en-us"
title = "Misinformation Platform"
theme = "hugo-coder"

[params]
author = "Bigdum Bape"
description = "Misinformation Platform"
keywords = "blog,developer,personal"
info = ["Social Engineer", "Magician"]
avatarURL = "images/avatar.jpg"
footerContent = "Enter a text here."
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2019

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/yourusername/"

[[params.social]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 2
url = "https://twitter.com/yourusername/"

# Menu items
[[menu.main]]
name = "About"
weight = 1
url = "/about/"

[[menu.main]]
name = "Blog"
weight = 2
url = "/posts/"

[[menu.main]]
name = "Projects"
weight = 3
url = "/projects/"
